### ISSUE TITLE
#108 issue的延伸

### ISSUE THREAD

**Issue by djnken** [VATPRC-Sector/VATPRC-Sector-Project#116]
**Description**
希望在ZBPE的Login Profile中加入ZBAA_W_APP及ZBAA_E_APP 以对应#108 （有没有可能每次更新时非必要的话不覆盖之前保存的Login Profile呢？）
另外 如果能根据callsign自动点亮对应小扇就更好了 现在开小扇仍然需要手动点亮：（

**Screenshots**
![image](https://user-images.githubusercontent.com/40542435/46063072-55022e80-c19e-11e8-8542-1c3955907007.png)

**Comment by mic12130** [comment]
- issue中的内容一般来说是待办事项，我们会在未来通过pull request的方式更新相关席位。
- 目前login profile由扇区构建工具根据package/情报区代码/channels文件自动生成，暂时无法实现不覆盖原文件。
- 分扇呼号不自动点亮主要是考虑到VATPRC在分扇时经常合并扇区（如ZXXX_1_APP实际管制范围为AP01还有AP02）。

**Comment by djnken** [comment]
Thx 👍
