### ISSUE TITLE
请求增加北京情报区内多个进近扇区

### ISSUE THREAD

**Issue by djnken** [VATPRC-Sector/VATPRC-Sector-Project#33]
发现在北京情报区内仅有北京、呼和、太原进近扇 希望可以增加天津、石家庄进近扇 ：）

**Screenshots**

**Comment by mic12130** [comment]
实际上北京情报区内已包含全部进近扇区的数据，但大部分没有边界数据（ARTCC LOW）
缺少边界数据的进近扇区有ZBTJ ZBHH ZBYN ZBSJ
