### ISSUE TITLE
更新西安进近扇区的MVA

### ISSUE THREAD

**Issue by djnken** [VATPRC-Sector/VATPRC-Sector-Project#53]
如题 发现现有的西安进近MVA不够精确 附图1为杰普森的RMA 图2为现在的扇区MVA

**Screenshots**
![img_0212](https://user-images.githubusercontent.com/40542435/42730634-e634b938-882b-11e8-91ce-572b7cecfdf1.png)
![image](https://user-images.githubusercontent.com/40542435/42730643-08270ac8-882c-11e8-87d4-e7ad2b52c5e9.png)

**Comment by mic12130** [comment]
MVA短期内不会更新

**Comment by mic12130** [comment]
这个issue已关闭，将由上述issue取代
