### ISSUE TITLE
绘制盐城机场地面扇

### ISSUE THREAD

**Issue by mic12130** [VATPRC-Sector/VATPRC-Sector-Project#74]
**Description**

盐城南阳机场（ZSYN）已有地景但缺少地面扇。

**Screenshots**

**Comment by websterzh** [comment]
已基本描绘完成，但是缺少新航站楼的停机位坐标数据（nr. 8-20），在获得准确的坐标之前无法继续进行。
另：建议提供地景链接以加入飞行员中心。

**Comment by mic12130** [comment]
地景

https://bbs.sinofsx.com/thread-129152-1-1.html

注意版权问题
